### ISSUE TITLE
Back to main menu after sleeping

### ISSUE THREAD

**Issue by xerman5** [hankmorgan/UnderworldExporter#10]
When I use the sleepingbag the first time I'm sent back to the main menu with no possibilities to come back to the current game status.

**Comment by hankmorgan** [comment]
Can't believe I missed this one. I put my postcutscene event code to return to main menu at the end of the victory cut-scene into the base cut-scene class. Fixed in the game code and will be sorted for the next release build which should be in the next fortnight.
