### ISSUE TITLE
Objects dissapearing permanently

### ISSUE THREAD

**Issue by xerman5** [hankmorgan/UnderworldExporter#11]
Objects and enemies dissapear in the game permanently. Let me explain.

1. I play the game and save it.
2. I continue playing and pick up an item. I die
3. I load the game from point 1 and the object from point 2 is not there anymore.

**Comment by hankmorgan** [comment]
Thanks.
I'm able to replicate this bug. Looks like the game data is not properly cleared when you die permanently. Loading the save a second time seems to load the objects properly. I'll get this fixed for the next release.

**Comment by hankmorgan** [comment]
Issue now fixed in code. Will be in next release.
