### ISSUE TITLE
Adjust mouselook sensitivity?

### ISSUE THREAD

**Issue by Espio419** [hankmorgan/UnderworldExporter#13]
Because it's really sensitive.

**Comment by hankmorgan** [comment]
Fixed for next release in config.ini file

Release should be available in a few days

**Comment by i30817** [comment]
This is usally a problem with multiple very different resolutions in modern monitors compared to the common at the time resolution and people scaling up the image (i keep my dosbox mouse settings to 35% of normal and my monitor is not that big). 

For example see this recent scummvm commit for handling this: https://github.com/scummvm/scummvm/pull/1111

**Comment by hankmorgan** [comment]
I'll look at that for a long term solution. At the moment I'll just leave the sensitivity setting in the config.ini.
