### ISSUE TITLE
Mouse cursor disappears during character creation

### ISSUE THREAD

**Issue by Kilg0reTr0ut** [hankmorgan/UnderworldExporter#15]
When I try to Create Character, and am at the stage where I type the Character name, the cursor disappears  when I enter the name, I can't click on anything. If I Esc back to the main screen, I can't click on anything so I have to ALT-F4. Also, I can't load save games from my dos games either. Speedstart works fine (but with the too high mouse sensitivity others have mentioned).

I am using the GOG version. I stream for GOG's twitch channel (https://www.twitch.tv/gogcom ) and I will be starting a playthrough of UU1 on Thursday and I would LOVE to get this working.

**Comment by Kilg0reTr0ut** [comment]
I discovered that I have to press E (the mouselook binded key) to get the mouse cursor back.

**Comment by hankmorgan** [comment]
Fixed in next release.
