### ISSUE TITLE
Exporter Tool

### ISSUE THREAD

**Issue by arwillis77** [hankmorgan/UnderworldExporter#18]
I have tried to create a map using the exporter tool using your instructions.  When I do the feature it scrolls a bunch of files but then I cannot find out where they are.  I do not think the files saves.  Am I doing something wrong?

**Comment by hankmorgan** [comment]
I don't really use the direct exporter anymore other than to build reports for file research.

Files should just save to the same folder as the executable.  Which mode are you using? The .FBX exporter might have been disabled during a commit about 6 months ago as it was preventing people from compiling their own versions to get at the artwork.

**Comment by arwillis77** [comment]
It was the Exporter.Tool from September 2017.  Selected option 11 FBX Export. The only file which seems affected is the uwexportlog. I am really enjoying your project though.  I did one of these on War in Middle Earth a few years back as i was interested in how they made the game.  Reverse engineering these old games is great insight into what went into making these games.
