### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by LordMaxin** [hankmorgan/UnderworldExporter#19]
I need some help here. I followed the instructions to the letter. I downloaded the UWE.release.1_03c.zip and put it in a folder, I extracted the GoG "ISO" to it's own fold, I gave the config file the path to the folder. and all it gives me every time is a Black Rectangle in the game select window.
![unity prob](https://user-images.githubusercontent.com/35699796/35232776-413df392-ff94-11e7-8baa-4cfa2374c1eb.png)

**Comment by hankmorgan** [comment]
Tested here with wrong paths and that what happens. Looks like you still have the wrong path entered. When you extract the contents of game.gog it will create a folder called game. Inside that folder you will see 2 more folders. UW and UW2. Point the paths to those folders as needed.
