### ISSUE TITLE
1.05 bugs/questions

### ISSUE THREAD

**Issue by Shafticus** [hankmorgan/UnderworldExporter#22]
I was able to make a quick run through the new version.  Some are questions, some are bugs.

General
Unable to know how many gold pieces in a pile, especially when picking up.  Doesn't vanilla show the number of coins?  Just have to enter a large number to make sure I get them all.
Is fall damage being calculated?
Killing monsters makes magical explosion animation?  I would have expected blood from a sword attack.  Not really a big issue, just wondering if that was intentional.
Switches can be reached without poles.  I think reach in general is much longer than in original game.
Killed rotworm had 2 corpses.  Appears to be all rotworms.  Was not like this in 1.04.
Left clicking gold in inventory - can use it as an item, appears to throw errors when trying to use it on something.  Not sure if this is intended.
Weight still not adjusting correctly.  Dropped gold, weight did not change.  Talked to Shak, weight was adjusted by how much gold I dropped.
Blood/magic animations from hitting monsters may appear above wrong monster if they are close.

Level 2
Scepter duplication upon picking up scepter in Goldthirst's treasury.  32 this time I think.  I just dropped them all and moved on.
Chest on level 2 is green.  Probably missing texture?
Shak still quotes high prices for items.  168 for Roderick's sword, yet he knows it is 30 when I come to pick it up.  Also quoted zero minutes to fix.
Shak seems to know the correct minutes left, but original time quote is bugged.

Level 4
Fall from a height when entering level 4 from level 3 near the bandit hideout. Also happens from level 7 to 8.  Looks like having more than 1 z value above a stair makes the game put it at the highest z level?

Level 6
Ranthru increased Lore by 12.  It said spellcasting would be increased, but no increase there. Lore is considered part of the magic abilities, maybe it is random?

Level 7
Unable to escape from jail.  Unable to talk to jailer.
When reloading game after being stuck, can't enter guard post at all. Message still stuck as if gate closed behind you. Exiting game entirely and then starting up again cleared this.

End game:
Missing some sprites
When returned to main menu after end cutscene, I have no cursor.

Best I can tell, the issues with missions have been fixed.  Did some out of order intentionally and did not have issues.  Was able to break Tyball's orb, rescue princess, bury Garamon, and use talismans.  Well done, sir.  Looks like exp count is displayed correctly.  Couldn't put my finger on it before, but looks better now.  The few spells I tried worked as well.

**Comment by hankmorgan** [comment]
Thanks for the feedback. I'm not sure if I'm supposed to send you a certificate of completion now.

I'm aware of most of these issues so I won't comment on them all.  The only major one I had not come across was the getting captured in the jail issue. I know you have to talk to a troll at one side of the bars to get free so I'll need to check that one out.

As far as I know Ranthru is meant to increase lore. I'll confirm the next time I load up a game in that area.
Shak's incorrect pricing is a weird one. The game uses string replacement codes to swap special characters in the text with variable values. If I fix the value for Shak I break the value for another NPC. It's very puzzling. The underlying data has the correct values except I don't know how the game arrives at the quotation for work.

I've been trying the hunt the sparkly hit impact for about six months now. Still unable to find a reason for it.

I'll check out the weights issue. I'm supposed to be pulling the values from the original game files but I think I need to check these item weights versus vanilla to see if there is some error in my implementation.

**Comment by zercomnexus** [comment]
i have the game on origin, but the exe file is ... mysteriously absent or built into the dosbox maybe? any advice on how to run it would be most welcome.

**Comment by hankmorgan** [comment]
Not familiar with the origin version. In general you should see a folder containing the file uw.exe and the folders DATA, CUTS, CRIT and SAVE0 to SAVE4. You don't actually need the exe file. The sub folders and their full contents are all you need.

Possibly this is like the gog version where the game files are stored in a zip archive that needs to be extracted. Looking at the dosbox.conf should show what is happening here.

**Comment by Kilg0reTr0ut** [comment]
1.06c looks fine so far except:
1: the black window if you cast Levitate more than once is back
2: not so much a bug, but there is a slight delay when loading a save. The new screen starts but the screen is locked for a few seconds before it kicks in. Then everything works normally.
3: jumping seems very high

**Comment by Kilg0reTr0ut** [comment]
1: I cast the Levitate spell, no potion or ring. It only happens if I cast the spell a second time,
2: gotcha
3: I'm a dumbass

**Comment by Kilg0reTr0ut** [comment]
Also, I notices the porticullis's are all red now. Is this intended?

**Comment by hankmorgan** [comment]
No. I must have mis-clicked on something somewhere. If you see out of place colours just ignore them as they are wip assets.
