### ISSUE TITLE
1.06c - Strange behavior of Tombstones and Crash Log

### ISSUE THREAD

**Issue by Zibit-Meowe** [hankmorgan/UnderworldExporter#24]
I was playing around on Lvl 5.  In the tombs, there were two [that I saw before crash] tombstones that were missing graphics.  When I clicked to view them, regardless of using context or manually clicking view, they showed a black screen.  A few minutes later or less, when swapping some gear, I received a hard crash.

I was not taken to the crash log upon answering the dialog box to do so.  But I did find one.  I'm attaching it below.

[Zibit_Lvl5_CrashLog.zip](https://github.com/hankmorgan/UnderworldExporter/files/1734102/Zibit_Lvl5_CrashLog.zip)

About ten minutes previous to this, I had observed the Alchemist scooting along a wall after turning in the Mines quest.  Not sure where he was trying to go, but he was heading toward the center of the level.  Also, a convo debug was generated after speaking with him.

[conversation_debug.txt](https://github.com/hankmorgan/UnderworldExporter/files/1734101/conversation_debug.txt)

Another strange issue I observed upon first trying 1.06c.  Upon entering combat mode on any save or new game, the screen did something strange.  The the interactive elements in the screen stayed the same, but the rest... ie, the text log, the 3d area border, etc... became transparent.  The full 3d area was zoomed to fit the full resolution of the screen.  The interactive elements still worked and just were shown atop the 3d layer.  This happened using a fresh copy of the game extracted to the folder, a new config, and copying the 1.06c zip back over the install.

Unfortunately, I derped and forgot to copy out my screenshot and lost it.  But this issue was resolved after freshly installing 1.06c again after complete deletion.  I'm assuming the bug was coming from some cached or temp files not overwritten if just extracting the install.  Otherwise, the resulting file structure, files, saves, etc... were all exactly the same.  Just figure I'd let you know in case you see it pop up from anyone else, but it hasn't happened again.

Take care and thanks for the hours of fun!

**Comment by hankmorgan** [comment]
Skimming the log. Part of this seems to be unity crapping itself. I'll check out all the graves to see if there is one that might be the cause of the issue.

Maybe check your keybinds for why the screen is doing that. Possibly the fullscreen toggle (default F) is the same as what you have for combat mode?

**Comment by Zibit-Meowe** [comment]
Re: F key... that's it!  I script my inputs for games like this when I want to do rebinds.  F is my combat key.

Now, my config.ini was NOT using F for fullscreen when it happened.  I had assigned F12.  I had triple checked this when it happened, so that makes me thing for some reason a cached copy of config from initial booting was not being updated.  I run the game first to make sure my install and paths are okay and THEN change the assigned button.

Is it possible a config.ini is being cached and not noticing that I am then changing the bind?  In the end, not a very big deal or priority.  _More likely_, it's possible the config.ini was open in notepad++ and there was some kind of access issue when the application is looking to the config.ini.  Just a guess.

No worries either way.
