### ISSUE TITLE
1.06c - interesting bug

### ISSUE THREAD

**Issue by Kilg0reTr0ut** [hankmorgan/UnderworldExporter#25]
I'm enclosing a save file you can check out. 

The key for the doors in prison (level 7)works fine on all the doors inside here. It's the grey key in the lower right backpack. The problem is that I normally keep all my keys in a pouch I keep in the second backpack on the top row. When I put this key in that pouch, it seems to combine with a couple of similar keys and is suddenly inaccessible.

As long as I keep that key out of that pouch, it works fine. Put it in that pouch, it's gone.
[SAVE3.zip](https://github.com/hankmorgan/UnderworldExporter/files/1735278/SAVE3.zip)

**Comment by hankmorgan** [comment]
I see whats going on here. Under the hood these two keys have the same object id but obviously open the different locks. I didn't think this was possible as I had assumed all keys were unique. 

It's an easy fix that I'll put in to the next build.

**Comment by hankmorgan** [comment]
Fixed.

**Comment by hankmorgan** [comment]
Hi Kilgore,

watching your most recent stream and I noticed you killed Garamon. This makes the game unwinnable if you don't answer his questions. Feel free to upload a save before the endgame sequence and I'll fix the quest flag for you.

I'll stop this issue from happening in a new release in a short while.

**Comment by Kilg0reTr0ut** [comment]
oops! I'm streaming in 7 minutes! Didn't realize that was Garamon! I thought our conversation was over and he was at rest!

**Comment by Kilg0reTr0ut** [comment]
well, I finished the game so I must have done something right :D

**Comment by hankmorgan** [comment]
Yeah. I'll check out your final stream to see what happens. Maybe it is enough to just bury Garamon but I was under the assumption you had to answer his questions first.

If you don't bury Garamon it is impossible to use the talismans before the final level.
