### ISSUE TITLE
Issue with 1.07c

### ISSUE THREAD

**Issue by Kilg0reTr0ut** [hankmorgan/UnderworldExporter#26]
I found one problem with the latest build. If you have mouselook active and then press F1 to access the main menu, you can't click on anything. You have to alt-tab out and close the program.

One other thing that has always been an issue is how fast some dialog flies by at the end of a conversation. When I got to the final cutscene at the end of the game the subtitles flew by too fast to read entirely.

Otherwise, it's good to have gotten to the end of the game. I will probably do another playthrough in a few months on GOG's Twitch channel. BTW, do you have any rough idea of when you will be getting back to working on UW2? I'd love to start playing that on my channel and help with betatesting that.

**Comment by hankmorgan** [comment]
UW2 is a long bit away. Although the core of the game is the same as UW1 there are some new systems such as an event system, a new output compression format for saving level data that I need to replicate and just general implementation of new features.

I'm aware of the menu bug and sorting the fix now and I'll look at the conversation timeout as well.

Thanks for all the feedback and I'll let you know when there are significant updates to UW2.
