### ISSUE TITLE
Standard Shader

### ISSUE THREAD

**Issue by danielgrom** [hankmorgan/UnderworldExporter#27]
This is more like a feature discussion. Why use the legacy shader and not the standard, is there any problem with that? I was thinking in making a texture pack for the game, it would be very nice to use all texture entries with the standard shader. I will try to change your code to test this. From what I got it you have a single function that loads the textures and based on the name you add a normal to the material, right?  I can add code that try to load extra textures for each standard shader entry, like if the name is uw01, then the function looks for uw01_m.tga for metalic entry, uw01_o.tga  for oclusion, uw_01_h.tga  for height, etc...

**Comment by hankmorgan** [comment]
No particular reason other than laziness in taking the time to understand the standard shader. I'll revisit the topic when I resume working on the project. I'll have to confess though that textures/shaders and related topics are arcane to me. But what you describe is basically correct but I've only implemented for the texture itself and normal map. extending to include other map types should be fairly easy.

**Comment by danielgrom** [comment]
There`s a 13 min video that explain it very well https://www.youtube.com/watch?v=fD_ho_ofY6A

**Comment by hankmorgan** [comment]
Thanks.
