### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by DoctorSbaitso** [hankmorgan/UnderworldExporter#29]
Tried the version previous and a little time with the recent release.  Here is some feedback on items you are likely already aware of.  if you want more feedback I suggest you participate here: http://www.rpgcodex.net/forums/index.php?threads/the-ultima-underworld-i-ii-thread.72708/page-38

The controls are obviously not the same. There is an odd (at first) hybrid interaction/mouselook mode that I got used to pretty quickly. Well done IMO but the ever-useful context sensitive cursor mode is not present. You have to switch to look mode, action mode while switching back and forth to mouselook and interactive mode. It is a good compromise as the different interaction modes are selectable via remappable hotkey so thumbs up on controls.

There is no bartering in the game as of now.

Nobody owns anything. There is no "Bedroll belonging to an Outcast" for example.
Because there are no possessions, there is no stealing and no repercussions for being spotted stealing.

Dialog is in but selection of dialog options by mouse is missing as of now. You must press the number corresponding to the option you want to select.

Dialog text colours are off.

Combat needs tweaking. Your characters is too strong at the start. Rats and worms die in one shot and I was able to clobber 3 human outcasts before dying at level 1.

Movement in general is very fluid but too fast by half. Creature combat was paced for someone who had to use the less nimble control mode and moved much slower in general. I suspect there will need to be some changes made there or it will just be piss easy.

Adjust the default light level darker in the ini file. It is set at 12 by default which is much brighter than the original. I suggest 4-5.

Your runebag comes full :?

The automap is fully realized but cursor position is offset from the quill

Some inventory bugs exist. I am carrying 259 lbs of stuff (but I am not really) and I can't pick up anything else.

Swimming is not there. You can spring-swim the whole level 1 waterway without drowning as level 0. There is no visual bobbing, you swim way too fast and there is zero risk of drowning.

**Comment by hankmorgan** [comment]
Thanks. From the sound of your issues you are possibly playing a older release of the game and if you have a full bag of runes then you are probably playing using the quick-start option which is basically a cheat character for testing.

I'll look over the other issues but they are mainly things I'm aware of.
