### ISSUE TITLE
Various bugs & such.

### ISSUE THREAD

**Issue by SabinStargem** [hankmorgan/UnderworldExporter#31]
BUGS
My playthrough uses a savefile from the original game, starting from the entrance to the dungeon.  This character was cheated to have max skills and attributes at LV1, with no further alterations.

#01B - Assigning functions to numbered keys like '1', '4', '7', and so on doesn't work.

#02B - If you assign the mouselook switch key to 'tab', there is some movement glitchiness after making a switch.

#03B - The game considers pillar sections in the Dwarf Level to be usable, though in practice they are not.

#04B - Adding annotations to the map can be quirky if you try to do this in succession.

#05B - The tracker skill's functionality seems broken.  Stood in front of a rat, and it would say nothing was there.  Ditto for headless.

#06B - When using 'readable' items, the text is read out twice.

#07B - The game is slow to transition from the end of a conversation to regular gameplay.

#08B - The octopuses fly above the water once you engage them in melee combat.  I think they are walking over the player, causing this oddness to happen.  A slight bit of their graphics fly above them while in the water.

#09B - You can walk over blocking boulders.

#10B - I died and was booted to the start menu, but wasn't able to choose options by mouse or keyboard.  Had to exit by force.

#11B - One of the Fly Potions that you get on the Dwarf Level causes the screen to go black.  (Playing later, this no longer happened.)

#12B - The red potion found on the Dwarf Level has no name.

#13B - A wand on the first floor has no names.  Has about 40 charges, I think.

#14B - Accidentally tried to lockpick some keys in my inventory, losing the picks in the process.  Wasn't able to replicate.  Suspect that mouse left-right clicking might be related.

#15B - Sometimes my attacks fully charge up almost instantly. Unintentional charging tends to happen when tabbed out of the game, and I get the impression some of that sticks around.

QUALITY OF LIFE SUGGESTIONS
With any luck, at least one of these would be decent.

#01S, "An Eye for Quality":  It would be nice if there were detailed tooltips when mousing over equipment and items.  Condition, enchantment, and numbers covering the effectiveness would be supremely handy.  The original game didn't have charts or useful descriptions about item quality.  Is a "Wooden Shield" better than a "Buckler of Minor Protection"?

#02S, "A Ring is Key":   Adding a keyring panel to the interface would be awesome.  Right-clicking it activates the keyring for use, left-clicking allows the player to open the 'bag' containing keys to check them, keys can be dragged and dropped.  Only items that act as keys are allowed to be placed in the bag.

#03S, "Chart's Counterattack":  Surrounding map annotations with a outline and allowing the player to drag them around would be useful for editing the map.

#04S, "I Smell a Rat":  It would be neat if the tracking skill could indicate creatures on the map.  Maybe a tooltip, too?

#05S, "Hammerfall"  Being able to choose a target condition for repairing would be a great time-saver.

**Comment by SabinStargem** [comment]
#16B - On level 3, by the north stairway by the water, there is an item.  It is partially submerged in the water, but unexaminable nor can it be picked up.

#17B - The splashes from waterfalls have text for being seen/used, even if they can't be.

#18B - On level 2, the room with two spiders at the top-center contains a potion.  There is a edible plant overlapping the potion, preventing it from being seen or picked up until the plant is eaten.

#19B - When peering through the orb on level 2, you can pick up the moonstone.

#20B - The healing fountain on level 2, in the northeast area floats.

#21B - On level 4, in the center-lower-leftish among waterfalls, there is a "Mail Shirt of None".

#22B - If you pick up and drop small boulders, they float in midair.  Destroying them will leave sling stones floating.

#23B - When you reload a game with floating sling stones, they vanish.

#24B - Dropped a 'gold coin' into a pile.  It vanished, changed the pile graphics, and the pile's amount remained at 81.

#25B - The center-left stairway on level 4 and 3 doesn't reliably trigger.

#26B - On level 4, there is a wand without a name.

#27B - There is a chain coif on level 5 without a name.

#28B - Couldn't ignite a candle and a torch.  On reloading, they could be ignited.  Both were partially used, and both were kept in a stack of their respective groups.

#29B - Damage effects and events can load into a saved game.  EG:  Walking on lava, loading, then dying from the damage.  The silver tree also kicks in right after reloading during the death screen.

#30B - You can destroy the glowing rocks in the Pac-Man maze on level 5 by attacking.  They also float, though I am not sure if it is intentional.

**Comment by hankmorgan** [comment]
Thanks for these. I'll take a look over them.
