### ISSUE TITLE
Couple bugs

### ISSUE THREAD

**Issue by siveon** [hankmorgan/UnderworldExporter#33]
1. On level 1 when you first see some water with the switch and small monster. If you walk towards land (the small land with said switch) on one side specifically you'll have slowed movement speed like you're on water - but you're on land. You can get out of this condition by jumping.

2. The spell runes go over the dragon in the UI. I don't remember if that was part of the original game.

3. The conversation text changes font size depending on the amount of text being given. I assume this is intentional? 

Thanks for this project! I really hope to see it polished to full potential.

**Comment by hankmorgan** [comment]
1 - I get that one a lot. Have never been able to track down a fix.
2- Ahh! Can't believe I've missed that. The Dragons are my favourite UI element!
3- Intentional for now. Getting all the text to fit on screen was the overriding concern.
