### ISSUE TITLE
Joystick controls in Unity player

### ISSUE THREAD

**Issue by MacLeod73** [hankmorgan/UnderworldExporter#34]
I've got movement drift in-game and it looks like there are a joystick axes set up in the Unity player that are overriding my WASD.  Are there ways of removing those?

**Comment by hankmorgan** [comment]
I'll look into this.

**Comment by eobet** [comment]
@hankmorgan was there a commit to fix this? I'd like to test it if so. The last release I see is still from 2018 and it still has the problems. The new Unity Input system should not have this problem, btw (I reported it to them some years ago and I believe they fixed it).

**Comment by hankmorgan** [comment]
I don't feel like the code is in a place where an official compiled release is possible. What I am going to do instead is just upload the project folder for use in the Unity 2020.
