### ISSUE TITLE
Missing Linux build for the latest release (1.08)

### ISSUE THREAD

**Issue by neuromancer** [hankmorgan/UnderworldExporter#35]
This re-implementation looks great!, I wonder if you can upload the latest release build for Linux.

Thanks!

**Comment by hankmorgan** [comment]
I'll try and do this in the next fortnight.

**Comment by bicobus** [comment]
I'd be interested to get one as well.

Using the latest available (1.07), a bug softlock the game when the menu shortcut (F1) is used while in mouse look (E). Basically, we can't escape mouselook and the game expect a cursor to select an element from the menu. I do not know if that is present in other builds or if it's been fixed upstream.

**Comment by Charadon** [comment]
Any update on the linux build? Would love to play this.

**Comment by hankmorgan** [comment]
I don't have a ready to go linux environment to test releases at the moment. I'll see what I can do though time permitting

**Comment by neuromancer** [comment]
Thanks!, please let us know here if you want to test some builds. :smile:
