### ISSUE TITLE
Object placement with larger textures

### ISSUE THREAD

**Issue by VaguelyPrecise** [hankmorgan/UnderworldExporter#36]
Hi,
I am trying to mod some of the original UW textures, starting with some objects. However, I noticed if I replace an object's texture with a higher-resolution file (e.g. 256x256), the object looks fine in inventory, but when placed on the ground it is oversized. Can you make objects retain their original size regardless of texture site?

**Comment by hankmorgan** [comment]
Yes. I will see what I can do here. Should be a straight forward change.

**Comment by hankmorgan** [comment]
Not as straight forward as I thought when I looked at the code as I skip loading the original image data when I detect a modded file. 
Having considered the change a bit I think what is best here is to actually save the file at the size you want it in game and not to force a resize by the engine. That way if you do eventually want a bigger object in game it's not constrained by the original data.

**Comment by VaguelyPrecise** [comment]
Good point about supporting different-sized objects, but I would also want to have higher-resolution objects without implying a diffent physical size. Suggestion: use a config file which provides a scale parameter for each modded texture, e.g. if you have an uwdata/objects_gr subdirectory, then in addition to loading modded texture files from there, also try to load a config file in that directory (e.g. uwdata/objects_gr/modconfig.txt) with contents like this:
001.tga 0.7
002.tga 1.35
(where the numbers are relative scales compared to whatever the standard rendering scale is).
