### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by psmitty7373** [hankmorgan/UnderworldExporter#37]
@hankmorgan, could you possibly upload another devenvironment.zip or possibly talk about how to go from your source to a working unity environment?

**Comment by hankmorgan** [comment]
No problem. I'll do this next weekend. Starting from the dev enviroment is best since there is some many UI elements to set up.

**Comment by hankmorgan** [comment]
I've uploaded my most recent version of the dev environment. I'm running Unity v2018.2.18f1 so it should work out of the box with that.

Only thing I can think of starting out is you may need to edit the shader files BasicUWShader and ColourReplacementShader to get the levels to render properly in the scene view. There is a comment in the shader files on the change you need to make.

Feel free to ask any questions in this thread.
