### ISSUE TITLE
1.08 - missing wall textures on "fast" and "fastest" graphics settings

### ISSUE THREAD

**Issue by VedVid** [hankmorgan/UnderworldExporter#38]
Hello.  
I'm using latest UnderworldExporter with GOG release of Ultima Underworld. On default settings ( The problem is that walls are invinsible, and I can see past them. As far as I know, changing game resolution and switching fullscreen doesn't help - I tried it all for "fastest" and "fast".

![image](https://user-images.githubusercontent.com/16949680/49160698-9db59f80-f327-11e8-8751-58314a031b49.png)

**Comment by hankmorgan** [comment]
I can see that myself when I set it to fastest. Does it work okay on the higher quality setting for you. I changed the shader for the textures on the last release so that is probably the issue.  The game is doing nothing too special graphically so putting to the best quality is recommended.

**Comment by VedVid** [comment]
On fast it still doesn't work. On higher settings everything looks fine.
