### ISSUE TITLE
No music

### ISSUE THREAD

**Issue by vilinder** [hankmorgan/UnderworldExporter#39]
I did make a folder on highlighted path and added the music back there. But the music doesn't really play. Using the latest release
![screenshot 2018-11-29 17 12 35](https://user-images.githubusercontent.com/42787342/49231248-374d8180-f3fa-11e8-9751-553df3041f58.png)

**Comment by hankmorgan** [comment]
On the 1.08 release you needed to have a trailing \ on paths. This is now fixed for the next release.
