### ISSUE TITLE
More issues (1.9)

### ISSUE THREAD

**Issue by siveon** [hankmorgan/UnderworldExporter#40]
Excited about the new release, although just wanted to get these out there since it did bug me.

1. The cursor "stamp" bug. Basically when you press anything the cursor just kind of lingers on the screen, like a stamp, until you press another thing and then it'll stamp on that part of where the cursor is situated. 
2. Dialogue bug. I can't seem to read all of the dialogue - just kind of cuts off. Maybe just add a basic scrollbar function? It's not something the original release had but it'd be a nice option. 
![capture](https://user-images.githubusercontent.com/36186313/49345888-e25b7680-f658-11e8-83fa-5967b1a30898.PNG)
Picture of both bugs(?)

Oh and this one, it's like that old windows bug where you see the same thing printed over and over again on the screen.

![image](https://user-images.githubusercontent.com/36186313/49345893-f7d0a080-f658-11e8-84e4-930f73c11110.png)

**Comment by siveon** [comment]
Oh yes I very much appreciate this project and I hope to see it grow larger in the future. It's the only project that got this far and I'm glad it did.

**Comment by gaspargazma** [comment]
Can confirm the first bugs. The mouse look thing doesn't bother me so much personally. Also the levers for the puzzle on the first level leading to Korianus Grave don't seem to do anything. Maybe I should stick with the original hacked version for my first playthrough or alternate between them. Anyway godspeed with this heroic project. Don't know shit much coding but I would have never deemed something like this possible. Such a pleasant surprise.

**Comment by hankmorgan** [comment]
Original dos version is still the best.
