### ISSUE TITLE
No uwe.exe

### ISSUE THREAD

**Issue by 3DMasterNL** [hankmorgan/UnderworldExporter#44]
The readme says to download zip and unpack it, put the paths in the .ini, and then run uwe.exe...

There's no uwe.exe.

There's also indeed no uwe.exe among the files you download as a zip on this github.

So...

What gives?

**Comment by jdougharty** [comment]
UWE.exe was renamed Underworld Exporter.exe for the latest build.

**Comment by 3DMasterNL** [comment]
Also doesn't exist, in fact there is no .exe file at all.

**Comment by tywilkerson** [comment]
Which file did you download 3DMasterNL?  I downloaded 'Windows.x64.V1_09.zip' and it contained Ultima World Exporter.exe. The source code files along with 'uw1.dev.20181202.zip'  do not contain any executable files. If you have in fact downloaded 'Windows.x65.V1_09.zip' and there are no Exes in it. You may want to make sure your antivirus isn't deleting the executables for some reason.

**Comment by jdougharty** [comment]
I agree with ty, it sounds like you got a hold of one of the uncompiled dev kits. You'll want to stop by here and grab the file with the filename he mentioned ('Windows.x64.V1_09.zip' ): https://github.com/hankmorgan/UnderworldExporter/releases
