### ISSUE TITLE
Stacking Items

### ISSUE THREAD

**Issue by 3DMasterNL** [hankmorgan/UnderworldExporter#45]
I don't see a header for simple questions anywhere (and hell, it might even be an issue) so I'll just post it here; I found a stack of two candles, then found another candle and I want to combine them into a stack of 3 candles; but I don't see how. It says left-click to combine/swap, but since it swaps I assume this is mixing of two ingredients and such kind of combine. Which still leaves the question; how do you stack the same items, and unstack them?

Also; how do you run/sprint. In the original w was running forward and s was walking forward; but that's no longer the case, the usual running method with the modern controls implemented in the exporter is holding shift, however that doesn't seem to do anything, and the controls in the initial exporter window doesn't mention it.

**Comment by gaspargazma** [comment]
My experience with the stacking is that it sometimes works and sometimes it doesn't. Also if you equip a stack of torches and try left click to light one of them the items disappear one by one untill you only have one left that actually ignites. For the other thing I think the default W movement is the old running.
