### ISSUE TITLE
macOS Release

### ISSUE THREAD

**Issue by Yzrsah** [hankmorgan/UnderworldExporter#46]
It would be great if Releases could include macOS.
Some macOS users would be grateful.

**Comment by baumhoto** [comment]
hi, created a macos version for latest release. you can find it here: 

[MacOS 1.09](https://github.com/baumhoto/UnderworldExporter/releases/tag/1.09)

**Comment by hankmorgan** [comment]
Cool. I don't have MacOs myself but this is great to see.
