### ISSUE TITLE
Released a build of the extractor

### ISSUE THREAD

**Issue by KarlClinckspoor** [hankmorgan/UnderworldExporter#48]
[Some time ago](https://github.com/hankmorgan/UnderworldExporter/issues/12) I mentioned I managed to build the extractor, and people have come to me asking for my binary, because they wanted to use the sprites for perler art or study. I decided to fork this project, create a branch, compile the extractor and [release it](https://github.com/KarlClinckspoor/UnderworldExporter/releases).

I'm pretty new to Git and Github, so I don't know the preferable way of going forward. Would this be interesting for the main project, warranting a pull request, or should I just keep it separate in my fork?

**Comment by hankmorgan** [comment]
Do what you want with it. I don't mind.
