### ISSUE TITLE
Upscale textures using ERSGAN

### ISSUE THREAD

**Issue by abedegno** [hankmorgan/UnderworldExporter#50]
It would be great to upscale the textures using a machine learning based upscaling system such as ERSGAN.
The project here:
https://github.com/Krischan74/RTCWHQ
Is designed for the Return to Castle Wolfenstein FPS, but may be repurposable for UUW?

**Comment by corpusc** [comment]
yes it can be tuned to work great for all old game textures.  in the duke4.net community discord, people are posting upscales for games like Duke3D, Blood, Shadow Warrior, Powerslave etc.

they look GREAT
