### ISSUE TITLE
Broken texture palettes when using SteamVR

### ISSUE THREAD

**Issue by Nin1** [hankmorgan/UnderworldExporter#52]
Thanks for this absolutely fantastic project! I'm trying to get it to work with SteamVR as a little learning project, which is simple enough to do in Unity. However, when I add the VR camera to the scene, the colour palettes for all the environment textures break:
![UWVR broken textures](https://user-images.githubusercontent.com/9250382/67619422-7c895780-f7f3-11e9-8112-42ef57374381.png)

**Comment by hankmorgan** [comment]
Not sure what I can do here. I don't have access to steam vr. The issue is almost certainly in the shader used for the textures. The project file should have a simpler shader that does'nt do palette animations that might work.
