### ISSUE TITLE
Will there be a fix for the mouse cursor issue in 1.08/1.09?

### ISSUE THREAD

**Issue by Kilg0reTr0ut** [hankmorgan/UnderworldExporter#53]
Hey Hank! I'm doing another stream/playthrough of UU this time at twitch.tv/gogcom. I'm using version 1.06 since the latest versions have the issue where the mouse curor stays on screen wherever you click. I don't suppose this will be fixed anytime soon? Are you still taking time off from this?

**Comment by hankmorgan** [comment]
I'll check this out.
