### ISSUE TITLE
Underworld Exporter.exe doesn't start

### ISSUE THREAD

**Issue by Stokviz** [hankmorgan/UnderworldExporter#54]
I am at a loss, nothing happens when I open the exe. Any clues?

**Comment by Kilg0reTr0ut** [comment]
What version are you running? Has it worked before?

**Comment by Stokviz** [comment]
Im running the 1.09 version and no, this is the first time I've installed it.

**Comment by Kilg0reTr0ut** [comment]
All I've ever had to do is unzip the file I've downloaded from here, then just run the exe. You still need to adjust the config.ini file to direct it to your Ultima Underworld directory, but at the least, the Unity engine should start up and take you to the main screen.
