### ISSUE TITLE
File not found text when Saving and Loading

### ISSUE THREAD

**Issue by thegameguy209** [hankmorgan/UnderworldExporter#55]
"File not found C:\GOG Games\Ultima Underworld\game\UW\SAVE4/DESC"
YET, the game does successfully save and load. I'm just forced to play with this text always on the screen anytime I wanna do that. This is my 2nd try reinstalling and setting it up. Last time it was looking for save slot 2, but I was always saving to slot 1. So the only folder I have is the SAVE1 folder with the file it's looking for inside.

Sorry if I'm missing any info you need, and thanks.

**Comment by Pitxi** [comment]
UW 1 starts counting from 0 for the save slots, but UnderworldExporter starts from 1. Maybe this is the reason for this issue, although it only complains about SAVE4, even if there is no SAVE# folder at all. Do the last error message overwrites the others?

**Comment by Pitxi** [comment]
I made a test and replicated the SAVE1 folder as SAVE4. Then the error complains about SAVE3. Replicating the other 3 folders from SAVE1 folder stopped the error message from showing.

**Comment by hankmorgan** [comment]
I'm guessing it assumes that the 4 save folders exist at start-up. A fresh install does not have these folders until a game is saved.

I think I fixed this in he code but not in the released build.
