### ISSUE TITLE
Still have trouble with GOG version

### ISSUE THREAD

**Issue by Caliban1971** [hankmorgan/UnderworldExporter#60]
Hi. I just bought UU1 & 2 on GOG and can't get the Underworld Exporter to recognize the .exe files. I've done everything that the readme file said to do, I think, but nothing worked. I tried following this old thread, but to no avail. Can you help me as well?

Thanks.

Ok

I see now where you are going wrong. You've downloaded the github repository for the source code and you are trying to run the dos era executable in that folder. 

Lets go back to the start of the process.

1. Download download windows.x64.v1_06c.zip from  [https://github.com/hankmorgan/UnderworldExporter/releases](https://github.com/hankmorgan/UnderworldExporter/releases) This is all you need to download to get started (without music)
2. Extract the zip file
3. Open config.ini in the folder you have extracted to.

4 .Now I can see you've found and extracted the game.gog file now so we'll skip over that step. So what you just need to do is repeat what you did to the config.ini file where you filled in the path to the original game as follows. 
Path_UW1=D:\Games\Ultima Underworld\Gog_game\UW\\
Note I've added a \ to the end of the path
5. You should be ready to go now. Just run UWE.exe in the extracted folder with the config.ini

_Originally posted by @hankmorgan in https://github.com/hankmorgan/UnderworldExporter/issues/23#issuecomment-366465503_

**Comment by hankmorgan** [comment]
All I can suggest is the path is still incorrect. All the data files not just the .exe have to be pointed to by the path in the config.ini.  Eg if you extract to c:\games\uw1\ then the config ini should point there and the files in that folder should be the all the game files.

**Comment by Caliban1971** [comment]
Hi Hank,

Thanks for the response. I was able to get it to work, and with music, but unfortunately ran into a problem someone else had where the screen resolution was stretched and made it nearly unplayable. But the mouse look worked great! I read that it might be due to my laptop being an AMD. I don't see any way to change the resolution, no option anywhere that I could access. I don't suppose you might know how to fix this particular issue?

**Comment by lookingglassed** [comment]
The screen resolution fix is to use a resolution provided by the Unity launcher. For example, 1080p is currently unsupported according to the latest release notes. The highest you can go is 1680 x 1050. If this doesnt work, edit the registry in HKEY_CURRENT_USER in the Underworld Exporter folder. There is a registry value for use native display resolution, change this value (decimal) to 0 and then relaunch the exporter and select the 1680 x 1050 resolution. The game will have some black borders but the UI will be at the proper proportions.
