### ISSUE TITLE
Save from Unity version crashes when restored in GOG version

### ISSUE THREAD

**Issue by vpelss** [hankmorgan/UnderworldExporter#61]
Save from Unity version crashes when restored in GOG version
[SAVE4.zip](https://github.com/hankmorgan/UnderworldExporter/files/4570677/SAVE4.zip)

**Comment by hankmorgan** [comment]
Save game compatabilty is not guaranteed to work unfortunately. There is still a lot of data I don't know about that can screw up.
UW1 can work most of the time but UW2 does not work at all I'm afraid.

**Comment by vpelss** [comment]
That's OK, I still love the project! You are doing god's work ;)
