### ISSUE TITLE
UI distorted

### ISSUE THREAD

**Issue by filipworksdev** [hankmorgan/UnderworldExporter#65]
![image](https://user-images.githubusercontent.com/36826319/99482857-e4dd3680-292a-11eb-986a-3c3c5d47e44c.png)

I am on the latest version V1_09 running GOG game using 1680 x 1050 resolution

Do you happen to know any fix?

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
I think I might have figured out a solution. 

This issue has happened randomly while playing the game. I am not sure why but if you exit then start in Window mode it will reset the UI position. Exit again and start in fullscreen mode and works again.

**Comment by hankmorgan** [comment]
Unfortunately you have to play in a 16:10 resolution. Unity UI screws up for me when I try and allow non 16:10 resolutions. Wish I knew how to fix.
