### ISSUE TITLE
Where in the world are these sound packs?

### ISSUE THREAD

**Issue by IttaBae** [hankmorgan/UnderworldExporter#68]
I've looked all over the internet, all over my files.  What can I do to get some ding-dang music in here?

**Comment by DaRodus** [comment]
UW1 Music pack
https://github.com/hankmorgan/UnderworldExporter/releases/download/1.07/Music.Packs.zip

**Comment by IttaBae** [comment]
thank you for showing me, but now there is a new problem in that trying to extract that zip gives me an error:
0x80004005 unspecified

**Comment by IttaBae** [comment]
Then I solved it by using ExtractNow
Case closed, I guess!
