### ISSUE TITLE
No Starting Music / No voice

### ISSUE THREAD

**Issue by Haakaah** [hankmorgan/UnderworldExporter#71]
Hello,
I Use win x 64 1.09 all working fine for the moment
But i have no music in the game starting & no voices (under unity )
Im reading read me
" 2.2 Soundtrack
		In release 1.05 the music files have been put into an external folder. This allows the use of custom soundtracks. A number of prebuilt sound tracks have been uploaded and these are
	- The PSX release of the soundtrack
	- An Sound blaster style soundtrack
	- A midi soundtrack.
To enable a sound track open config.ini and find the UW1_Soundbank setting. Enter the path to the folder containing the music.

The music files must be in .ogg format and named 01.ogg to 15.ogg  Refer to the SB16 soundtrack for exact files to use."

But i can't find any folder with music on it i have the environement sounds in game
I have only a folder "SOUND" with 79 files on it
I have the GOG game
I thing im not understand something but i don't know what

Thanks for job
Thanks for help

**Comment by DaRodus** [comment]
Hi Haakaah,

- [ ] You must first download the UW1 DOS

[](https://mega.nz/file/DG4jFABC#H9DtRuvdB6SuciVOF4-33HXTMZCy2PTeP5mEv53M9Hk)

- [ ] The music pack

[](https://mega.nz/file/bawVBQgS#r-jMUsMniqU2FTxSGP1_WQF_dbA-tqsWdUmxb28RHGs)

You can can use my version, you have to do that if you install it on a hard disk root C: \. 
If this is not the case, you must change the file "config.ini"

- [ ] [](https://mega.nz/file/aXgDEQiR#yW8LSM9zbKCETcEx-FEtjSWccvthsySWChauDxZXt9A)

Best regards

Rodus

**Comment by Haakaah** [comment]
Good job !
Thx for help :)
