### ISSUE TITLE
Option to invert mouse-look?

### ISSUE THREAD

**Issue by wildweasel486** [hankmorgan/UnderworldExporter#8]
Just heard of this and began play in earnest. Impressive work! There is one thing getting in the way, though, and that's that I have found no way to flip the Y-axis of mouse-look. Are there plans to expand the options menu or config files to include such a thing?

**Comment by hankmorgan** [comment]
Keybindings were literally only added in the last day or two. Assuming there isn't a pre-existing option in the Unity player launch window settings for this I'll look into this for future releases. Thanks.

**Comment by hankmorgan** [comment]
Option in next release.
