### ISSUE TITLE
Linux binaries?

### ISSUE THREAD

**Issue by Demorde** [hankmorgan/UnderworldExporter#9]
Hello,

Would it be possible to get some precompiled Linux binaries for this?

**Comment by KarlClinckspoor** [comment]
Yes please, and please a precompiled binary of the extractor itself, not only of the Unity game. Or at least some instructions to compile it. I get a ton of errors when I try compiling.

**Comment by hankmorgan** [comment]
I'll take a look at Linux builds. Most of my current focus is bringing UW2 support up to scratch so you might have to be patient unless you take the dev files on the release page and build your own from those...

I've also just pushed a build of the extractor tool to the releases page. This is a tool I've used for internal use mainly so it is provided as-is, so be prepared for bugs and strange behaviour. When you run the tool there will be an output log in a file called uw-export.log. You just have to edit the file gamepaths.txt to point to your installations. (extract the gog.com game.gog file if you have that first). 

If you're trying to compile your own version of the extractor from what I remember the only external dependency is the autodesk fbx sdk. The code isn't great so I'm sorry I'm not a bigger help here.

**Comment by hankmorgan** [comment]
Just to update on this issue. I have a build running on a debian laptop. I need to test some more before releasing but it's looking good so far.

**Comment by hankmorgan** [comment]
First linux build now uploaded.

**Comment by Demorde** [comment]
![uwe1](https://user-images.githubusercontent.com/2192159/36224120-d0273e32-1183-11e8-854a-59bcde883b7d.png)

It'll launch, but all I get is a black screen when I try to load up UUW1.

**Comment by hankmorgan** [comment]
Looks like it can't find the game files. I really need to add an error message for that to help here.

Look at ~/.config/unity3d/Underworld Exporter/Underworld Export/player.log

It will indicate what file(s) the game is failing to open.  If you have the gog version then you need to extract the game.gog file to a new folder and point to that instead. You should be pointing to the folder containing uw.exe and has subfolders for crit, cuts and data containing all the game files.

The file paths are case sensitive as well. I've assumed that all the game files are all in CAPS as that is the way it is on my system.

**Comment by Demorde** [comment]
I can confirm I got it working, the issue was spaces in the path setting.
